apiVersion: v1
entries:
  test-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-07-06T06:47:28.069448-03:00"
    description: A Helm chart for Kubernetes
    digest: ef4e6a6c6e8a4023cc2d37ca1fe9ff2d6cd2f296d2b310aa69cbd814e73ba0d3
    name: test-app
    type: application
    urls:
    - https://charts.hellnet.com.br/charts/test-app-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-06T06:47:28.068233-03:00"
