{{- if and .Values.containerPort .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellnet-service.fullname" . }}
  labels:
    {{- include "hellnet-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hellnet-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
