apiVersion: v2
name: test-app
description: A simple test chart for the hellnet Helm repository
type: application
version: 0.1.1
appVersion: "1.0.0"
annotations:
  artifacthub.io/changes: |
    - Added ArtifactHub metadata annotations
  artifacthub.io/maintainers: |
    - name: guilhermelinosp
      email: guilhermelino@hellnet.com.br
  artifacthub.io/repository: hellnet
